# Generate letter_polys.scad: one exact outline polygon per FONT letter,
# equal to the union of that glyph's pixel squares as drawn by glyph2d()
# in font.scad (px = font_px = 1.1, bleed = 0.12). Integer units of
# 0.01mm so the rectilinear union is exact; emitted as mm floats.
# Usage: gen_letter_polys.py <font.scad> <letter_polys.scad>
import re, sys

PX = 110      # font_px = 1.1mm  (keep in sync with wordclock.scad)
HALF = 61     # (1.1 + 0.12)/2 mm — glyph2d()'s px + bleed

font_path, out_path = sys.argv[1:3]
font = {}
src = open(font_path).read()
for m in re.finditer(r'\["([A-Z])",\[([^\]]*)\]\]', src):
    ch, rows = m.group(1), re.findall(r'"([01]{5})"', m.group(2))
    assert len(rows) == 7, ch
    font[ch] = rows

def glyph_loops(rows):
    boxes = []
    for r in range(7):
        for c in range(5):
            if rows[r][c] == "1":
                xc, yc = (c - 2) * PX, (3 - r) * PX
                boxes.append((xc - HALF, xc + HALF, yc - HALF, yc + HALF))
    xs = sorted({v for b in boxes for v in b[:2]})
    ys = sorted({v for b in boxes for v in b[2:]})
    nx, ny = len(xs) - 1, len(ys) - 1
    def covered(i, j):
        if i < 0 or j < 0 or i >= nx or j >= ny:
            return False
        cx, cy = (xs[i] + xs[i+1]) / 2, (ys[j] + ys[j+1]) / 2
        return any(x0 < cx < x1 and y0 < cy < y1 for x0, x1, y0, y1 in boxes)
    cov = [[covered(i, j) for j in range(ny)] for i in range(nx)]
    # boundary edges, interior kept on the left of travel direction
    edges = {}
    for i in range(nx):
        for j in range(ny):
            if not cov[i][j]:
                continue
            x0, x1, y0, y1 = xs[i], xs[i+1], ys[j], ys[j+1]
            if not covered(i, j-1): edges[(x0, y0)] = (x1, y0)  # bottom, east
            if not covered(i, j+1): edges[(x1, y1)] = (x0, y1)  # top, west
            if not covered(i-1, j): edges[(x0, y1)] = (x0, y0)  # left, south
            if not covered(i+1, j): edges[(x1, y0)] = (x1, y1)  # right, north
    loops = []
    while edges:
        start = next(iter(edges))
        loop, p = [], start
        while True:
            q = edges.pop(p)
            loop.append(p)
            p = q
            if p == start:
                break
        # merge collinear runs
        out = []
        n = len(loop)
        for k in range(n):
            a, b, c = loop[k-1], loop[k], loop[(k+1) % n]
            if (a[0] == b[0] == c[0]) or (a[1] == b[1] == c[1]):
                continue
            out.append(b)
        area = sum(out[k-1][0]*out[k][1] - out[k][0]*out[k-1][1]
                   for k in range(len(out))) / 2
        assert area > 0, "hole found (CW loop) — stencil bridge missing?"
        loops.append(out)
    return loops

with open(out_path, "w") as f:
    f.write("// GENERATED by gen_letter_polys.py — exact pixel-union outlines\n")
    f.write("// of font.scad glyphs at px=1.1 bleed=0.12, one polygon per loop.\n")
    f.write("LETTER_POLYS = [\n")
    for ch in sorted(font):
        loops = glyph_loops(font[ch])
        ls = ", ".join(
            "[" + ", ".join("[%g, %g]" % (x/100, y/100) for x, y in lp) + "]"
            for lp in loops)
        f.write('["%s", [%s]],\n' % (ch, ls))
    f.write("];\n")
print("letter_polys: %d letters -> %s" % (len(font), out_path))
